language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: JtSNHrbd8GhSNjLcSUEvNkNaJIrdmXOZ5HkZI40aGniQqLviK3BI+kHmkxzQDISA/1b2TsJwfyhscq1/nEvcsT3mGQv1gN+gZEM9xLWmO6A4T0e8xkt6KhqbvPlYOZSZ4gQaOgNRxHexu38rQVyKW9eQ4nelPEnzR/V7aqQIKx95tswKkMxt8NWEJh/Sd29I6zjgR+QXziAWVjD0YWRKl9d6onfYbjSvxgvH4qKMg7D/+N0EtLcIFxuQp/BH4GETSBLetyNIRfu4AstmZlD8++PIKKeja26IdjpktJQrpMdpspGZxH89CJ6/sG6J6a3P4uhC1B/Dh1dSAMraDNIR35nGPUOmPGzmn69W72TSNkbyh39q5GglNBFy/62mzuxyKd38nNPcU+OCGOgN3D1fSOGLObmIRp6KqaLhgP/akwIpZZTis8CUOjP6GsigrAyyXtSxHKvd1q0HJMsuUEqvDLbN1nn/rHqwpbStX3HTfvhw1GkXFbStiP230MS+qN3FzH3lGZKJwziUmk96tRxsNjj3p2AP7Fb/oORl6DVl8vfnqPrhp9WSRogh/lP2se4vcEPuVp8NRIr2xZySnGtDg/SI+O/gfDEweUniQzq5+m2NBAnDqDxZpqznzrFrh1KiRzTVoTVLu62ed01Tl63m1Zqh1MOlAZ+Sm+1PcnjHT/A=
