language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: Lc/TSj9rLYqnzIugNfJN4madifb2nq4rrpHenBzz1uIQDkQaHlGzsguANx3VerlhN6TwbhjguVB64v7jNhbbdS9hiWyWqV3ChAFPrL/TV3lJ9Ji3s2I6YRmzHLur3iPp3OGrYTfxi0K043u3oHqZuvBkEQl+XEsWuJDSlfvonf31Xw2HCJ+bN0c9k2+eF4fbGaSwTUlQtQS0wuwmi5p+W7PNz5OWV8K7lyoaQbi1+PADMQdpC/feF6CAEJNak5SqKmG6gUAKnWJSETM1PpwCKHajt8c26qBPApwM+5zicGV2PARbM7H4Jzb0LnHetDCaDBZtydoVwJ7z4OloBgDe0Pvh8f5v+sSvNhta8m8mBzG6qplVRBWUlbCk6oUV4ArKgT4BOAazWf20NflCNPBI+arU5uRDvkeMiNkr/CcNMQvy/WN9EAmLBlb8314JHRDEID4sYSbMlynywXEXu8n61SYORR3dO0W9YS/r2hf7F+NTlPFO5B6U3r4KF+bwqyWoaTrL2VwAqwteXpTNiByptmn2OjPNqjV6Suu/Fx3SazTw1/bs0brKwL63ZONR40XAP9BjVg9UOSYgX34HxyRM8GsjrezVVt2x1wwGdlC03TeI625/0u8U5YoYEbKHQPzh3MN5FHIBnrR1SRDR3C49sqs8GaWKSHQK9AmLGJ2zEeg=
