language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: bhMcawKvPosnCR78LCzP1ghTxklOpui8eJYIRux3ALqycUf9nqeVIJqvEx1dEvdQvL4jhVIXsVjC6gmhrJaSobH+wp4SqrEOLv7jhko13FRw2SS2lQ03dG56l2CTmu6/WiW+bXBRb7CCWakleE1c75VAbVgGZIJRx7mohxkW+qk0Dsij3qRPmIKzPympIFXYfulyZ6p/8YstqpXBJOEpMyfdpkEauVIoHbDJG3Me3pui85UdyFOFt98Bf1On51oCfJ7EOhtK72ve0uxuX1UguXEqM5Ak+7YGIcxBXlZ2/8yZGe15JSUH9aWyupQBnG6gtqoQVsd7J1cMDYGCJQuJ9iPCqJKIxOg85RSn9EGRXXnT8ylQfoPWLMlujVAa8I947XdTsHcRQCV7N/xbzgN0MDWS7fqZ7az3NBabuRo8ufdffC3uG8+mHo8nUIa+kBH8rOGSsN/o8pwFBtvXLtGj9+ljqnUa8I8xbqh4Ae1mWPIS37EhcryDy6cqCZ7EuOtR6nzWxdFXCanA1fx3lb4RIwgZivlSFWdWN16NaSw7rJBkXim0mH/94FGIQsc7akwyeLmTyO8N5xJycvNsiYguFlNmyRRtXZjcZlUT6IzmUgMZDeXHPpA3PIQJLPuVPeokjV6f8NzdDLdXF+PRNJJqGwMg7cQ26cJisC8jAJJF+5M=
